### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by sdruskat**
Great draft all in all, this PR changes just a few things, like stressing the importance of citing the software one uses a bit more.

### CODE REVIEW

**Comment by sdruskat** [comment]
@jspaaks This is good to go from my side. Do you want me to submit to the SSI blog once you have finished editing?

**Comment by jspaaks** [comment]
Let me check with @jmaassen how we want to do this / when it should be published

**Comment by jspaaks** [comment]
OK, did some minor update to the text. Also talked to @jmaassen and our communications person. They prefer to publish on medium first (https://blog.esciencecenter.nl/), then reblog on SSI. If that's alright with you, go ahead and fill in the form/CMS/system for the SSI blog (but don't publish just yet).

**Comment by sdruskat** [comment]
No probs. I'll set up the SSI post and tell them to sit on it for the minute. Thanks!

**Comment by sdruskat** [comment]
Your changes aren't pushed yet, right?

**Pull request merged**
